id: P010549
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-19 20:55:29.393494
source_metadata:
  id: bdr:W1KG23851
  title: ཨ་ཁུ་བསྟན་པའི་གཏམ་རྒྱུད།
  author: ''
  volumes:
    72dd7d7b29744210a83748ff3668ac5c:
      image_group_id: I1KG24065
      title: ''
      volume_number: 1
      total_pages: 298
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
