id: IC5BF3AEC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T12:18:14+00:00'
last_modified: '2022-06-08T14:25:09.574533+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG23851
  title: ཨ་ཁུ་བསྟན་པའི་གཏམ་རྒྱུད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    9D9D:
      image_group_id: I1KG24065
      title: ''
      total_pages: 298
      order: 1
      base_file: 9D9D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
